### ISSUE TITLE
TODO for making grpc supports php5 and php7

### ISSUE THREAD

**Issue by thinkerou** [thinkerou/grpc-php7#4]
Have committed to `grpc/grpc` https://github.com/grpc/grpc/pull/7464

Hi @stanley-cheung , I list some thoughts about grpc-php7 merge grpc/src/php and begin to prepare work.

Because we will not create dir(like `grpc/src/php/ext/grpc-php7`) but use macro, so we need to consider how reduce code and ensure security.

For reducing dup-code, we firstly need to do:
- [X] use `char*` and `size_t or int` instead of `zend_string`. it will crash if use `int` about `s` on php7.
- [X] unify `size_t` and `int` to `grpc_int` about `s` 
- [X] not use `ZEND_HASH_FOREACH_*_VAL` macro or use macro for differentiate php version
- [X] use `TSRMLS_*` macro for ensure code security on php5
- [X] define macro `grpc_long`, it is `zend_long` on php7 and is `long` on php5
- [X] unify `return_value`, because it errors on `php5`, like: `ChannelCredentials::createDefault`
- [X] unify `zend_object_store_get_object` and `Z_WRAPPED_XXX_P`
- [X] make `MAKE_STD_ZVAL` use on php7
- [X] unify `free_wrapped_grpc_xxx` function
- [X] unify `grpc_php_wrap_xxx` function
- [X] unify `create_wrapped_grpc_xxx` function
- [X] unify `wrap object struct` by macro

and wrap some macros....

**Comment by stanley-cheung** [comment]
Frankly, I am OK with some duplicate code for now. We can shrink them later. The most important thing is to get both php5 and php7 compiled in the same package. 

We have a chance to get this into the 1.0.0 release and I'd rather us do that than spending too much time on reducing duplicate code for now. We can always do that later as it's a transparent non-breaking change.

**Comment by thinkerou** [comment]
OK, we use your method now.

**Comment by thinkerou** [comment]
Some discusses https://github.com/thinkerou/grpc-php7/pull/3 about this.

**Comment by thinkerou** [comment]
@stanley-cheung `define macro grpc_long, it is zend_long on php7 and is long on php5 => I have done but not commit now.` => the macro should not use startwith `grpc_`, right? Because the core function name of grpc start with `grpc_`. we use `php_grpc_`, like: `php_grpc_long`?

**Comment by stanley-cheung** [comment]
is this going to be a macro? or an actual function? `php_grpc_long` sounds good

also, just to confirm, we shouldn't be doing any more work in this repo. All the work should be on the `grpc/grpc` repo, correct?

**Comment by thinkerou** [comment]
it is macro, like:

```
#ifndef PHP7_WRAPPER_GRPC_H
#define PHP7_WRAPPER_GRPC_H

#if PHP_MAJOR_VERSION < 7

#define php_grpc_int int
#define php_grpc_long long
#define PHP_GRPC_MAKE_STD_ZVAL(pzv) MAKE_STD_ZVAL(pzv)

#else

#define php_grpc_int size_t
#define php_grpc_long zend_long
#define PHP_GRPC_MAKE_STD_ZVAL(pzv) zval _stack_zval_##pzv; pzv = &(_stack_zval_##pzv)

#endif /* PHP_MAJOR_VERSION */

#endif /* PHP7_WRAPPER_GRPC_H */
```

Yeth, now I not commit and I debug.

And we can use the follow to reduce dup code and clear code:

```
PHP_METHOD(Timeval, __construct) {
  wrapped_grpc_timeval *timeval = Z_WRAPPED_GRPC_TIMEVAL_P(getThis());
  grpc_long microseconds;

  /* "l" == 1 long */
  if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "l", &microseconds) ==
      FAILURE) {
    zend_throw_exception(spl_ce_InvalidArgumentException,
                         "Timeval expects a long", 1 TSRMLS_CC);
    return;
  }
  gpr_timespec time = gpr_time_from_micros(microseconds, GPR_TIMESPAN);
  memcpy(&timeval->wrapped, &time, sizeof(gpr_timespec));
}
```

**Comment by stanley-cheung** [comment]
looks good to me

**Comment by thinkerou** [comment]
For reducing duplicated codes, we need to use macro wrap public codes.
And for clearing some macro need to write special files, then TODO list the follow:

- [ ] `zend_object_store_get_object` and `Z_WRAPPED_GRPC_XXX_P`, like: write `timeval.h` file

- [ ] etc
